### ISSUE TITLE
Can't access structure information for ABS datasets

### ISSUE THREAD

**Issue by bedewilson** [dr-leo/pandaSDMX#218]
I'm new to SDMX so not sure if this issue is related to me, the ABS or pandaSDMX. If there's something to implement though I'm happy to assist with a PR.

I have been able to access ABS data successfully, but not the structure information. I am presuming this is due to the non-implementation of the `dataflow` endpoint - but correct me if that's not the case.

The ABS does return structure information in `req.response` though (see code below). I also tried using the dataflow function by adding `force=True`, and got the following error:

`requests.exceptions.HTTPError: 400 Client Error: Semantic Error for url: https://stat.data.abs.gov.au/sdmx-json/dataflow/ABS/ABS_ERP_COMP_SA/latest?references=all`

Note that the ABS does provide a a dataflow endpoint in `req.response` of [https://stat.data.abs.gov.au/sdmx-json/dataflow/ABS_ERP_COMP_SA/all](https://stat.data.abs.gov.au/sdmx-json/dataflow/ABS_ERP_COMP_SA/all), which works, but is slightly different to the error from pandaSDMX above.

Is it just that the URL for the dataflow is constructed differently in pandaSDMX to what the ABS have implemented? And/or is there another way to extract the structure information using pandaSDMX given that it is sent in the response?

I have been able to parse the JSON manually to get this information but this is just a hack.

### Illustrative code
```python
import pandasdmx as sdmx

abs = sdmx.Request('ABS')

resource_id = 'ABS_ERP_COMP_SA'
key = '10.SA3.31701.A/all'
params = {
    'detail': 'Full',
    'dimensionAtObservation': 'AllDimensions'
}

# Can request ABS data successfully like so.
# Note that the structure information is not available
# (e.g. the ASGS_2016 column returns an SA3 id of 31701,
# but I can't access the SA3 name of 'Toowoomba')
req = abs.data(resource_id=resource_id, key=key, params=params)
data = req.to_pandas()
print('ABS population data:\n', data)

# This information is available in the response object though
response = req.response.json()
print('Structure information from req.response:\n', response['structure']['dimensions']['observation'])

# Forcing the dataflow request generates an error because
# the assumed URL doesn't match the actual ABS endpoint
data_flow = abs.dataflow(resource_id='ABS_ERP_COMP_SA', force=True)
```
### Output
```
ABS population data:
 POP_COMP  REGIONTYPE  ASGS_2016  FREQUENCY  TIME_PERIOD
10        SA3         31701      A          2017           154805.0
                                            2018           156706.0
                                            2019           158446.0
                                            2020           159991.0
Name: value, dtype: float64 

Structure information from req.response:
 [{'keyPosition': 0, 'id': 'POP_COMP', 'name': 'Population Component', 'values': [{'id': '10', 'name': 'Estimated Resident Population'}]}, {'keyPosition': 1, 'id': 'REGIONTYPE', 'name': 'Geography Level', 'values': [{'id': 'SA3', 'name': 'Statistical Area Level 3'}]}, {'keyPosition': 2, 'id': 'ASGS_2016', 'name': 'Region', 'values': [{'id': '31701', 'name': 'Toowoomba'}]}, {'keyPosition': 3, 'id': 'FREQUENCY', 'name': 'Frequency', 'values': [{'id': 'A', 'name': 'Annual'}], 'role': 'FREQ'}, {'id': 'TIME_PERIOD', 'name': 'Time', 'values': [{'id': '2017', 'name': '2017'}, {'id': '2018', 'name': '2018'}, {'id': '2019', 'name': '2019'}, {'id': '2020', 'name': '2020'}], 'role': 'TIME_PERIOD'}] 

Traceback (most recent call last):
  File "/home/bede/Documents/Development/pandasdmx-test/test.py", line 26, in <module>
    data_flow = abs.dataflow(resource_id='ABS_ERP_COMP_SA', force=True)
  File "/home/bede/.local/share/virtualenvs/pandasdmx-test-37ei8JeN/lib/python3.8/site-packages/pandasdmx/api.py", line 440, in get
    response.raise_for_status()
  File "/home/bede/.local/share/virtualenvs/pandasdmx-test-37ei8JeN/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Semantic Error for url: https://stat.data.abs.gov.au/sdmx-json/dataflow/ABS/ABS_ERP_COMP_SA/latest?references=all
```

**Comment by dr-leo** [comment]
Fixed in v1.8.0. See #222
